services: 
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php